<?php

//Make sure it was called inside a file.
if ($x_IN_FILE != 1)
  exit;

$locations = array(
	array(
		'name' => 'Philippines',
		'regions' => array(
			array(
				'name' => 'Abra',
				'areacode' => '74',
				'cities' => array(
					array('name' => 'Bangued',),
					array('name' => 'Boliney',),
					array('name' => 'Bucay',),
					array('name' => 'Bucloc',),
					array('name' => 'Daguioman',),
					array('name' => 'Danglas',),
					array('name' => 'Dolores',),
					array('name' => 'La Paz',),
					array('name' => 'Lacub',),
					array('name' => 'Lagangilang',),
					array('name' => 'Lagayan',),
					array('name' => 'Langiden',),
					array('name' => 'Licuan-Baay',),
					array('name' => 'Luba',),
					array('name' => 'Malibcong',),
					array('name' => 'Manabo',),
					array('name' => 'Peñarrubia',),
					array('name' => 'Pidigan',),
					array('name' => 'Pilar',),
					array('name' => 'Sallapadan',),
					array('name' => 'San Isidro',),
					array('name' => 'San Juan',),
					array('name' => 'San Quintin',),
					array('name' => 'Tayum',),
					array('name' => 'Tineg',),
					array('name' => 'Tubo',),
					array('name' => 'Villaviciosa',),
				),
			),
			array(
				'name' => 'Agusan del Norte',
				'areacode' => '85',
				'cities' => array(
					array('name' => 'Butuan City',),
					array('name' => 'Buenavista',),
					array('name' => 'Cabadbaran',),
					array('name' => 'Carmen',),
					array('name' => 'Jabonga',),
					array('name' => 'Kitcharao',),
					array('name' => 'Las Nieves',),
					array('name' => 'Magallanes',),
					array('name' => 'Nasipit',),
					array('name' => 'Remedios T. Romualdez',),
					array('name' => 'Santiago',),
					array('name' => 'Tubay',),
				),
			),
			array(
				'name' => 'Agusan del Sur',
				'areacode' => '85',
				'cities' => array(
					array('name' => 'Bayugan',),
					array('name' => 'Bunawan',),
					array('name' => 'Esperanza',),
					array('name' => 'La Paz',),
					array('name' => 'Loreto',),
					array('name' => 'Prosperidad',),
					array('name' => 'Rosario',),
					array('name' => 'San Francisco',),
					array('name' => 'San Luis',),
					array('name' => 'Santa Josefa',),
					array('name' => 'Sibagat',),
					array('name' => 'Talacogon',),
					array('name' => 'Trento',),
					array('name' => 'Veruela',),
				),
			),
			array(
				'name' => 'Aklan',
				'areacode' => '36',
				'cities' => array(
					array('name' => 'Altavas',),
					array('name' => 'Balete',),
					array('name' => 'Banga',),
					array('name' => 'Batan',),
					array('name' => 'Buruanga',),
					array('name' => 'Ibajay',),
					array('name' => 'Kalibo',),
					array('name' => 'Lezo',),
					array('name' => 'Libacao',),
					array('name' => 'Madalag',),
					array('name' => 'Makato',),
					array('name' => 'Malay',),
					array('name' => 'Malinao',),
					array('name' => 'Nabas',),
					array('name' => 'New Washington',),
					array('name' => 'Numancia',),
					array('name' => 'Tangalan',),
				),
			),
			array(
				'name' => 'Albay',
				'areacode' => '52',
				'cities' => array(
					array('name' => 'Legazpi City',),
					array('name' => 'Ligao City',),
					array('name' => 'Tabaco City',),
					array('name' => 'Bacacay',),
					array('name' => 'Camalig',),
					array('name' => 'Daraga',),
					array('name' => 'Guinobatan',),
					array('name' => 'Jovellar',),
					array('name' => 'Libon',),
					array('name' => 'Malilipot',),
					array('name' => 'Malinao',),
					array('name' => 'Manito',),
					array('name' => 'Oas',),
					array('name' => 'Pio Duran',),
					array('name' => 'Polangui',),
					array('name' => 'Rapu-Rapu',),
					array('name' => 'Santo Domingo',),
					array('name' => 'Tiwi',),
				),
			),
			array(
				'name' => 'Antique',
				'areacode' => '36',
				'cities' => array(
					array('name' => 'Anini-y',),
					array('name' => 'Barbaza',),
					array('name' => 'Belison',),
					array('name' => 'Bugasong',),
					array('name' => 'Caluya',),
					array('name' => 'Culasi',),
					array('name' => 'Hamtic',),
					array('name' => 'Laua-an',),
					array('name' => 'Libertad',),
					array('name' => 'Pandan',),
					array('name' => 'Patnongon',),
					array('name' => 'San Jose',),
					array('name' => 'San Remigio',),
					array('name' => 'Sebaste',),
					array('name' => 'Sibalom',),
					array('name' => 'Tibiao',),
					array('name' => 'Tobias Fornier',),
					array('name' => 'Valderrama',),
				),
			),
			array(
				'name' => 'Apayao',
				'areacode' => '74',
				'cities' => array(
					array('name' => 'Calanasan',),
					array('name' => 'Conner',),
					array('name' => 'Flora',),
					array('name' => 'Kabugao',),
					array('name' => 'Luna',),
					array('name' => 'Pudtol',),
					array('name' => 'Santa Marcela',),
				),
			),
			array(
				'name' => 'Aurora',
				'areacode' => '42',
				'cities' => array(
					array('name' => 'Baler',),
					array('name' => 'Casiguran',),
					array('name' => 'Dilasag',),
					array('name' => 'Dinalungan',),
					array('name' => 'Dingalan',),
					array('name' => 'Dipaculao',),
					array('name' => 'Maria Aurora',),
					array('name' => 'San Luis',),
				),
			),
			array(
				'name' => 'Basilan',
				'areacode' => '62',
				'cities' => array(
					array('name' => 'Isabela City',),
					array('name' => 'Akbar',),
					array('name' => 'Al-Barka',),
					array('name' => 'Hadji Mohammad Ajul',),
					array('name' => 'Hadji Muhtamad',),
					array('name' => 'Lamitan',),
					array('name' => 'Lantawan',),
					array('name' => 'Maluso',),
					array('name' => 'Sumisip',),
					array('name' => 'Tabuan-Lasa',),
					array('name' => 'Tipo-Tipo',),
					array('name' => 'Tuburan',),
					array('name' => 'Ungkaya Pukan',),
				),
			),
			array(
				'name' => 'Bataan',
				'areacode' => '47',
				'cities' => array(
					array('name' => 'Balanga City',),
					array('name' => 'Abucay',),
					array('name' => 'Bagac',),
					array('name' => 'Dinalupihan',),
					array('name' => 'Hermosa',),
					array('name' => 'Limay',),
					array('name' => 'Mariveles',),
					array('name' => 'Morong',),
					array('name' => 'Orani',),
					array('name' => 'Orion',),
					array('name' => 'Pilar',),
					array('name' => 'Samal',),
				),
			),
			array(
				'name' => 'Batanes',
				'areacode' => '78',
				'cities' => array(
					array('name' => 'Basco',),
					array('name' => 'Itbayat',),
					array('name' => 'Ivana',),
					array('name' => 'Mahatao',),
					array('name' => 'Sabtang',),
					array('name' => 'Uyugan',),
				),
			),
			array(
				'name' => 'Batangas',
				'areacode' => '43',
				'cities' => array(
					array('name' => 'Batangas City',),
					array('name' => 'Lipa City',),
					array('name' => 'Tanauan City',),
					array('name' => 'Agoncillo',),
					array('name' => 'Alitagtag',),
					array('name' => 'Balayan',),
					array('name' => 'Balete',),
					array('name' => 'Bauan',),
					array('name' => 'Calaca',),
					array('name' => 'Calatagan',),
					array('name' => 'Cuenca',),
					array('name' => 'Ibaan',),
					array('name' => 'Laurel',),
					array('name' => 'Lemery',),
					array('name' => 'Lian',),
					array('name' => 'Lobo',),
					array('name' => 'Mabini',),
					array('name' => 'Malvar',),
					array('name' => 'Mataas na Kahoy',),
					array('name' => 'Nasugbu',),
					array('name' => 'Padre Garcia',),
					array('name' => 'Rosario',),
					array('name' => 'San Jose',),
					array('name' => 'San Juan',),
					array('name' => 'San Luis',),
					array('name' => 'San Nicolas',),
					array('name' => 'San Pascual',),
					array('name' => 'Santa Teresita',),
					array('name' => 'Santo Tomas',),
					array('name' => 'Taal',),
					array('name' => 'Talisay',),
					array('name' => 'Taysan',),
					array('name' => 'Tingloy',),
					array('name' => 'Tuy',),
				),
			),
			array(
				'name' => 'Benguet',
				'areacode' => '74',
				'cities' => array(
					array('name' => 'Baguio City',),
					array('name' => 'Atok',),
					array('name' => 'Bakun',),
					array('name' => 'Bokod',),
					array('name' => 'Buguias',),
					array('name' => 'Itogon',),
					array('name' => 'Kabayan',),
					array('name' => 'Kapangan',),
					array('name' => 'Kibungan',),
					array('name' => 'La Trinidad',),
					array('name' => 'Mankayan',),
					array('name' => 'Sablan',),
					array('name' => 'Tuba',),
					array('name' => 'Tublay',),
				),
			),
			array(
				'name' => 'Biliran',
				'areacode' => '53',
				'cities' => array(
					array('name' => 'Almeria',),
					array('name' => 'Biliran',),
					array('name' => 'Cabucgayan',),
					array('name' => 'Caibiran',),
					array('name' => 'Culaba',),
					array('name' => 'Kawayan',),
					array('name' => 'Maripipi',),
					array('name' => 'Naval',),
				),
			),
			array(
				'name' => 'Bohol',
				'areacode' => '38',
				'cities' => array(
					array('name' => 'Tagbilaran City',),
					array('name' => 'Alburquerque',),
					array('name' => 'Alicia',),
					array('name' => 'Anda',),
					array('name' => 'Antequera',),
					array('name' => 'Baclayon',),
					array('name' => 'Balilihan',),
					array('name' => 'Batuan',),
					array('name' => 'Bien Unido',),
					array('name' => 'Bilar',),
					array('name' => 'Buenavista',),
					array('name' => 'Calape',),
					array('name' => 'Candijay',),
					array('name' => 'Carmen',),
					array('name' => 'Catigbian',),
					array('name' => 'Clarin',),
					array('name' => 'Corella',),
					array('name' => 'Cortes',),
					array('name' => 'Dagohoy',),
					array('name' => 'Danao',),
					array('name' => 'Dauis',),
					array('name' => 'Dimiao',),
					array('name' => 'Duero',),
					array('name' => 'Garcia Hernandez',),
					array('name' => 'Guindulman',),
					array('name' => 'Inabanga',),
					array('name' => 'Jagna',),
					array('name' => 'Jetafe',),
					array('name' => 'Lila',),
					array('name' => 'Loay',),
					array('name' => 'Loboc',),
					array('name' => 'Loon',),
					array('name' => 'Mabini',),
					array('name' => 'Maribojoc',),
					array('name' => 'Panglao',),
					array('name' => 'Pilar',),
					array('name' => 'Pres. Carlos P. Garcia',),
					array('name' => 'Sagbayan',),
					array('name' => 'San Isidro',),
					array('name' => 'San Miguel',),
					array('name' => 'Sevilla',),
					array('name' => 'Sierra Bullones',),
					array('name' => 'Sikatuna',),
					array('name' => 'Talibon',),
					array('name' => 'Trinidad',),
					array('name' => 'Tubigon',),
					array('name' => 'Ubay',),
					array('name' => 'Valencia',),
				),
			),
			array(
				'name' => 'Bukidnon',
				'areacode' => '88',
				'cities' => array(
					array('name' => 'Malaybalay City',),
					array('name' => 'Valencia City',),
					array('name' => 'Baungon',),
					array('name' => 'Cabanglasan',),
					array('name' => 'Damulog',),
					array('name' => 'Dangcagan',),
					array('name' => 'Don Carlos',),
					array('name' => 'Impasug-Ong',),
					array('name' => 'Kadingilan',),
					array('name' => 'Kalilangan',),
					array('name' => 'Kibawe',),
					array('name' => 'Kitaotao',),
					array('name' => 'Lantapan',),
					array('name' => 'Libona',),
					array('name' => 'Malitbog',),
					array('name' => 'Manolo Fortich',),
					array('name' => 'Maramag',),
					array('name' => 'Pangantucan',),
					array('name' => 'Quezon',),
					array('name' => 'San Fernando',),
					array('name' => 'Sumilao',),
					array('name' => 'Talakag',),
				),
			),
			array(
				'name' => 'Bulacan',
				'areacode' => '44',
				'cities' => array(
					array('name' => 'Malolos City',),
					array('name' => 'Meycauayan City',),
					array('name' => 'San Jose del Monte City',),
					array('name' => 'Angat',),
					array('name' => 'Balagtas',),
					array('name' => 'Baliuag',),
					array('name' => 'Bocaue',),
					array('name' => 'Bulacan',),
					array('name' => 'Bustos',),
					array('name' => 'Calumpit',),
					array('name' => 'Doña Remedios Trinidad',),
					array('name' => 'Guiguinto',),
					array('name' => 'Hagonoy',),
					array('name' => 'Marilao',),
					array('name' => 'Norzagaray',),
					array('name' => 'Obando',),
					array('name' => 'Pandi',),
					array('name' => 'Paombong',),
					array('name' => 'Plaridel',),
					array('name' => 'Pulilan',),
					array('name' => 'San Ildefonso',),
					array('name' => 'San Miguel',),
					array('name' => 'San Rafael',),
					array('name' => 'Santa Maria',),
				),
			),
			array(
				'name' => 'Cagayan',
				'areacode' => '78',
				'cities' => array(
					array('name' => 'Tuguegarao City',),
					array('name' => 'Abulug',),
					array('name' => 'Alcala',),
					array('name' => 'Allacapan',),
					array('name' => 'Amulung',),
					array('name' => 'Aparri',),
					array('name' => 'Baggao',),
					array('name' => 'Ballesteros',),
					array('name' => 'Buguey',),
					array('name' => 'Calayan',),
					array('name' => 'Camalaniugan',),
					array('name' => 'Claveria',),
					array('name' => 'Enrile',),
					array('name' => 'Gattaran',),
					array('name' => 'Gonzaga',),
					array('name' => 'Iguig',),
					array('name' => 'Lal-Lo',),
					array('name' => 'Lasam',),
					array('name' => 'Pamplona',),
					array('name' => 'Peñablanca',),
					array('name' => 'Piat',),
					array('name' => 'Rizal',),
					array('name' => 'Sanchez-Mira',),
					array('name' => 'Santa Ana',),
					array('name' => 'Santa Praxedes',),
					array('name' => 'Santa Teresita',),
					array('name' => 'Santo Niño',),
					array('name' => 'Solana',),
					array('name' => 'Tuao',),
				),
			),
			array(
				'name' => 'Camarines Norte',
				'areacode' => '54',
				'cities' => array(
					array('name' => 'Basud',),
					array('name' => 'Capalonga',),
					array('name' => 'Daet',),
					array('name' => 'Jose Panganiban',),
					array('name' => 'Labo',),
					array('name' => 'Mercedes',),
					array('name' => 'Paracale',),
					array('name' => 'San Lorenzo Ruiz',),
					array('name' => 'San Vicente',),
					array('name' => 'Santa Elena',),
					array('name' => 'Talisay',),
					array('name' => 'Vinzons',),
				),
			),
			array(
				'name' => 'Camarines Sur',
				'areacode' => '54',
				'cities' => array(
					array('name' => 'Iriga City',),
					array('name' => 'Naga City',),
					array('name' => 'Baao',),
					array('name' => 'Balatan',),
					array('name' => 'Bato',),
					array('name' => 'Bombon',),
					array('name' => 'Buhi',),
					array('name' => 'Bula',),
					array('name' => 'Cabusao',),
					array('name' => 'Calabanga',),
					array('name' => 'Camaligan',),
					array('name' => 'Canaman',),
					array('name' => 'Caramoan',),
					array('name' => 'Del Gallego',),
					array('name' => 'Gainza',),
					array('name' => 'Garchitorena',),
					array('name' => 'Goa',),
					array('name' => 'Lagonoy',),
					array('name' => 'Libmanan',),
					array('name' => 'Lupi',),
					array('name' => 'Magarao',),
					array('name' => 'Milaor',),
					array('name' => 'Minalabac',),
					array('name' => 'Nabua',),
					array('name' => 'Ocampo',),
					array('name' => 'Pamplona',),
					array('name' => 'Pasacao',),
					array('name' => 'Pili',),
					array('name' => 'Presentacion',),
					array('name' => 'Ragay',),
					array('name' => 'Sagñay',),
					array('name' => 'San Fernando',),
					array('name' => 'San Jose',),
					array('name' => 'Sipocot',),
					array('name' => 'Siruma',),
					array('name' => 'Tigaon',),
					array('name' => 'Tinambac',),
				),
			),
			array(
				'name' => 'Camiguin',
				'areacode' => '88',
				'cities' => array(
					array('name' => 'Catarman',),
					array('name' => 'Guinsiliban',),
					array('name' => 'Mahinog',),
					array('name' => 'Mambajao',),
					array('name' => 'Sagay',),
				),
			),
			array(
				'name' => 'Capiz',
				'areacode' => '36',
				'cities' => array(
					array('name' => 'Roxas City',),
					array('name' => 'Cuartero',),
					array('name' => 'Dao',),
					array('name' => 'Dumalag',),
					array('name' => 'Dumarao',),
					array('name' => 'Ivisan',),
					array('name' => 'Jamindan',),
					array('name' => 'Ma-ayon',),
					array('name' => 'Mambusao',),
					array('name' => 'Panay',),
					array('name' => 'Panitan',),
					array('name' => 'Pilar',),
					array('name' => 'Pontevedra',),
					array('name' => 'President Roxas',),
					array('name' => 'Sapi-an',),
					array('name' => 'Sigma',),
					array('name' => 'Tapaz',),
				),
			),
			array(
				'name' => 'Catanduanes',
				'areacode' => '52',
				'cities' => array(
					array('name' => 'Bagamanoc',),
					array('name' => 'Baras',),
					array('name' => 'Bato',),
					array('name' => 'Caramoran',),
					array('name' => 'Gigmoto',),
					array('name' => 'Pandan',),
					array('name' => 'Panganiban',),
					array('name' => 'San Andres',),
					array('name' => 'San Miguel',),
					array('name' => 'Viga',),
					array('name' => 'Virac',),
				),
			),
			array(
				'name' => 'Cavite',
				'areacode' => '46',
				'cities' => array(
					array('name' => 'Cavite City',),
					array('name' => 'Tagaytay City',),
					array('name' => 'Trece Martires City',),
					array('name' => 'Alfonso',),
					array('name' => 'Amadeo',),
					array('name' => 'Bacoor',),
					array('name' => 'Carmona',),
					array('name' => 'Dasmariñas',),
					array('name' => 'Gen. Mariano Alvarez',),
					array('name' => 'Gen. Emilio Aguinaldo',),
					array('name' => 'Gen. Trias',),
					array('name' => 'Imus',),
					array('name' => 'Indang',),
					array('name' => 'Kawit',),
					array('name' => 'Magallanes',),
					array('name' => 'Maragondon',),
					array('name' => 'Mendez',),
					array('name' => 'Naic',),
					array('name' => 'Noveleta',),
					array('name' => 'Rosario',),
					array('name' => 'Silang',),
					array('name' => 'Tanza',),
					array('name' => 'Ternate',),
				),
			),
			array(
				'name' => 'Cebu',
				'areacode' => '32',
				'cities' => array(
					array('name' => 'Cebu City',),
					array('name' => 'Danao City',),
					array('name' => 'Lapu-Lapu City',),
					array('name' => 'Mandaue City',),
					array('name' => 'Talisay City',),
					array('name' => 'Toledo City',),
					array('name' => 'Alcantara',),
					array('name' => 'Alcoy',),
					array('name' => 'Alegria',),
					array('name' => 'Aloguinsan',),
					array('name' => 'Argao',),
					array('name' => 'Asturias',),
					array('name' => 'Badian',),
					array('name' => 'Balamban',),
					array('name' => 'Bantayan',),
					array('name' => 'Barili',),
					array('name' => 'Bogo',),
					array('name' => 'Boljoon',),
					array('name' => 'Borbon',),
					array('name' => 'Carcar',),
					array('name' => 'Carmen',),
					array('name' => 'Catmon',),
					array('name' => 'Compostela',),
					array('name' => 'Consolacion',),
					array('name' => 'Cordoba',),
					array('name' => 'Daanbantayan',),
					array('name' => 'Dalaguete',),
					array('name' => 'Dumanjug',),
					array('name' => 'Ginatilan',),
					array('name' => 'Liloan',),
					array('name' => 'Madridejos',),
					array('name' => 'Malabuyoc',),
					array('name' => 'Medellin',),
					array('name' => 'Minglanilla',),
					array('name' => 'Moalboal',),
					array('name' => 'Naga',),
					array('name' => 'Oslob',),
					array('name' => 'Pilar',),
					array('name' => 'Pinamungahan',),
					array('name' => 'Poro',),
					array('name' => 'Ronda',),
					array('name' => 'Samboan',),
					array('name' => 'San Fernando',),
					array('name' => 'San Francisco',),
					array('name' => 'San Remigio',),
					array('name' => 'Santa Fe',),
					array('name' => 'Santander',),
					array('name' => 'Sibonga',),
					array('name' => 'Sogod',),
					array('name' => 'Tabogon',),
					array('name' => 'Tabuelan',),
					array('name' => 'Tuburan',),
					array('name' => 'Tudela',),
				),
			),
			array(
				'name' => 'Compostela Valley',
				'areacode' => '87',
				'cities' => array(
					array('name' => 'Compostela',),
					array('name' => 'Laak',),
					array('name' => 'Mabini',),
					array('name' => 'Maco',),
					array('name' => 'Maragusan',),
					array('name' => 'Mawab',),
					array('name' => 'Monkayo',),
					array('name' => 'Montevista',),
					array('name' => 'Nabunturan',),
					array('name' => 'New Bataan',),
					array('name' => 'Pantukan',),
				),
			),
			array(
				'name' => 'Cotabato',
				'areacode' => '64',
				'cities' => array(
					array('name' => 'Kidapawan City',),
					array('name' => 'Alamada',),
					array('name' => 'Aleosan',),
					array('name' => 'Antipas',),
					array('name' => 'Arakan',),
					array('name' => 'Banisilan',),
					array('name' => 'Carmen',),
					array('name' => 'Kabacan',),
					array('name' => 'Libungan',),
					array('name' => 'M\'Lang',),
					array('name' => 'Magpet',),
					array('name' => 'Makilala',),
					array('name' => 'Matalam',),
					array('name' => 'Midsayap',),
					array('name' => 'Pigkawayan',),
					array('name' => 'Pikit',),
					array('name' => 'President Roxas',),
					array('name' => 'Tulunan',),
				),
			),
			array(
				'name' => 'Davao del Norte',
				'areacode' => '84',
				'cities' => array(
					array('name' => 'Panabo City',),
					array('name' => 'Island Garden City of Samal',),
					array('name' => 'Tagum City',),
					array('name' => 'Asuncion',),
					array('name' => 'Braulio E. Dujali',),
					array('name' => 'Carmen',),
					array('name' => 'Kapalong',),
					array('name' => 'New Corella',),
					array('name' => 'San Isidro',),
					array('name' => 'Santo Tomas',),
					array('name' => 'Talaingod',),
				),
			),
			array(
				'name' => 'Davao del Sur',
				'areacode' => '82',
				'cities' => array(
					array('name' => 'Davao City',),
					array('name' => 'Digos City',),
					array('name' => 'Bansalan',),
					array('name' => 'Don Marcelino',),
					array('name' => 'Hagonoy',),
					array('name' => 'Jose Abad Santos',),
					array('name' => 'Kiblawan',),
					array('name' => 'Magsaysay',),
					array('name' => 'Malalag',),
					array('name' => 'Malita',),
					array('name' => 'Matanao',),
					array('name' => 'Padada',),
					array('name' => 'Santa Cruz',),
					array('name' => 'Santa Maria',),
					array('name' => 'Sarangani',),
					array('name' => 'Sulop',),
				),
			),
			array(
				'name' => 'Davao Oriental',
				'areacode' => '87',
				'cities' => array(
					array('name' => 'Baganga',),
					array('name' => 'Banaybanay',),
					array('name' => 'Boston',),
					array('name' => 'Caraga',),
					array('name' => 'Cateel',),
					array('name' => 'Governor Generoso',),
					array('name' => 'Lupon',),
					array('name' => 'Manay',),
					array('name' => 'Mati',),
					array('name' => 'San Isidro',),
					array('name' => 'Tarragona',),
				),
			),
			array(
				'name' => 'Dinagat Islands',
				'areacode' => '86',
				'cities' => array(
					array('name' => 'Basilisia (Rizal)',),
					array('name' => 'Cagdianao',),
					array('name' => 'Dinagat',),
					array('name' => 'Libjo (Albor)',),
					array('name' => 'Loreto',),
					array('name' => 'San Jose',),
					array('name' => 'Tubajon',),
				),
			),
			array(
				'name' => 'Eastern Samar',
				'areacode' => '55',
				'cities' => array(
					array('name' => 'Arteche',),
					array('name' => 'Balangiga',),
					array('name' => 'Balangkayan',),
					array('name' => 'Borongan',),
					array('name' => 'Can-avid',),
					array('name' => 'Dolores',),
					array('name' => 'General MacArthur',),
					array('name' => 'Giporlos',),
					array('name' => 'Guiuan',),
					array('name' => 'Hernani',),
					array('name' => 'Jipapad',),
					array('name' => 'Lawaan',),
					array('name' => 'Llorente',),
					array('name' => 'Maslog',),
					array('name' => 'Maydolong',),
					array('name' => 'Mercedes',),
					array('name' => 'Oras',),
					array('name' => 'Quinapondan',),
					array('name' => 'Salcedo',),
					array('name' => 'San Julian',),
					array('name' => 'San Policarpo',),
					array('name' => 'Sulat',),
					array('name' => 'Taft',),
				),
			),
			array(
				'name' => 'Guimaras',
				'areacode' => '33',
				'cities' => array(
					array('name' => 'Buenavista',),
					array('name' => 'Jordan',),
					array('name' => 'Nueva Valencia',),
					array('name' => 'San Lorenzo',),
					array('name' => 'Sibunag',),
				),
			),
			array(
				'name' => 'Ifugao',
				'areacode' => '74',
				'cities' => array(
					array('name' => 'Aguinaldo',),
					array('name' => 'Alfonso Lista',),
					array('name' => 'Asipulo',),
					array('name' => 'Banaue',),
					array('name' => 'Hingyon',),
					array('name' => 'Hungduan',),
					array('name' => 'Kiangan',),
					array('name' => 'Lagawe',),
					array('name' => 'Lamut',),
					array('name' => 'Mayoyao',),
					array('name' => 'Tinoc',),
				),
			),
			array(
				'name' => 'Ilocos Norte',
				'areacode' => '77',
				'cities' => array(
					array('name' => 'Laoag City',),
					array('name' => 'Adams',),
					array('name' => 'Bacarra',),
					array('name' => 'Badoc',),
					array('name' => 'Bangui',),
					array('name' => 'Banna',),
					array('name' => 'Burgos',),
					array('name' => 'Carasi',),
					array('name' => 'Currimao',),
					array('name' => 'Dingras',),
					array('name' => 'Dumalneg',),
					array('name' => 'Marcos',),
					array('name' => 'Nueva Era',),
					array('name' => 'Pagudpud',),
					array('name' => 'Paoay',),
					array('name' => 'Pasuquin',),
					array('name' => 'Piddig',),
					array('name' => 'Pinili',),
					array('name' => 'San Nicolas',),
					array('name' => 'Sarrat',),
					array('name' => 'Solsona',),
					array('name' => 'Vintar',),
				),
			),
			array(
				'name' => 'Ilocos Sur',
				'areacode' => '77',
				'cities' => array(
					array('name' => 'Candon City',),
					array('name' => 'Vigan City',),
					array('name' => 'Alilem',),
					array('name' => 'Banayoyo',),
					array('name' => 'Bantay',),
					array('name' => 'Burgos',),
					array('name' => 'Cabugao',),
					array('name' => 'Caoayan',),
					array('name' => 'Cervantes',),
					array('name' => 'Galimuyod',),
					array('name' => 'Gregorio Del Pilar',),
					array('name' => 'Lidlidda',),
					array('name' => 'Magsingal',),
					array('name' => 'Nagbukel',),
					array('name' => 'Narvacan',),
					array('name' => 'Quirino',),
					array('name' => 'Salcedo',),
					array('name' => 'San Emilio',),
					array('name' => 'San Esteban',),
					array('name' => 'San Ildefonso',),
					array('name' => 'San Juan',),
					array('name' => 'San Vicente',),
					array('name' => 'Santa',),
					array('name' => 'Santa Catalina',),
					array('name' => 'Santa Cruz',),
					array('name' => 'Santa Lucia',),
					array('name' => 'Santa Maria',),
					array('name' => 'Santiago',),
					array('name' => 'Santo Domingo',),
					array('name' => 'Sigay',),
					array('name' => 'Sinait',),
					array('name' => 'Sugpon',),
					array('name' => 'Suyo',),
					array('name' => 'Tagudin',),
				),
			),
			array(
				'name' => 'Iloilo',
				'areacode' => '33',
				'cities' => array(
					array('name' => 'Passi City',),
					array('name' => 'Iloilo City',),
					array('name' => 'Ajuy',),
					array('name' => 'Alimodian',),
					array('name' => 'Anilao',),
					array('name' => 'Badiangan',),
					array('name' => 'Balasan',),
					array('name' => 'Banate',),
					array('name' => 'Barotac Nuevo',),
					array('name' => 'Barotac Viejo',),
					array('name' => 'Batad',),
					array('name' => 'Bingawan',),
					array('name' => 'Cabatuan',),
					array('name' => 'Calinog',),
					array('name' => 'Carles',),
					array('name' => 'Concepcion',),
					array('name' => 'Dingle',),
					array('name' => 'Dueñas',),
					array('name' => 'Dumangas',),
					array('name' => 'Estancia',),
					array('name' => 'Guimbal',),
					array('name' => 'Igbaras',),
					array('name' => 'Janiuay',),
					array('name' => 'Lambunao',),
					array('name' => 'Leganes',),
					array('name' => 'Lemery',),
					array('name' => 'Leon',),
					array('name' => 'Maasin',),
					array('name' => 'Miagao',),
					array('name' => 'Mina',),
					array('name' => 'New Lucena',),
					array('name' => 'Oton',),
					array('name' => 'Pavia',),
					array('name' => 'Pototan',),
					array('name' => 'San Dionisio',),
					array('name' => 'San Enrique',),
					array('name' => 'San Joaquin',),
					array('name' => 'San Miguel',),
					array('name' => 'San Rafael',),
					array('name' => 'Santa Barbara',),
					array('name' => 'Sara',),
					array('name' => 'Tigbauan',),
					array('name' => 'Tubungan',),
					array('name' => 'Zarraga',),
				),
			),
			array(
				'name' => 'Isabela',
				'areacode' => '78',
				'cities' => array(
					array('name' => 'Cauayan City',),
					array('name' => 'Santiago City',),
					array('name' => 'Alicia',),
					array('name' => 'Angadanan',),
					array('name' => 'Aurora',),
					array('name' => 'Benito Soliven',),
					array('name' => 'Burgos',),
					array('name' => 'Cabagan',),
					array('name' => 'Cabatuan',),
					array('name' => 'Cordon',),
					array('name' => 'Delfin Albano',),
					array('name' => 'Dinapigue',),
					array('name' => 'Divilacan',),
					array('name' => 'Echague',),
					array('name' => 'Gamu',),
					array('name' => 'Ilagan',),
					array('name' => 'Jones',),
					array('name' => 'Luna',),
					array('name' => 'Maconacon',),
					array('name' => 'Mallig',),
					array('name' => 'Naguilian',),
					array('name' => 'Palanan',),
					array('name' => 'Quezon',),
					array('name' => 'Quirino',),
					array('name' => 'Ramon',),
					array('name' => 'Reina Mercedes',),
					array('name' => 'Roxas',),
					array('name' => 'San Agustin',),
					array('name' => 'San Guillermo',),
					array('name' => 'San Isidro',),
					array('name' => 'San Manuel',),
					array('name' => 'San Mariano',),
					array('name' => 'San Mateo',),
					array('name' => 'San Pablo',),
					array('name' => 'Santa Maria',),
					array('name' => 'Santo Tomas',),
					array('name' => 'Tumauini',),
				),
			),
			array(
				'name' => 'Kalinga',
				'areacode' => '74',
				'cities' => array(
					array('name' => 'Balbalan',),
					array('name' => 'Lubuagan',),
					array('name' => 'Pasil',),
					array('name' => 'Pinukpuk',),
					array('name' => 'Rizal',),
					array('name' => 'Tabuk',),
					array('name' => 'Tanudan',),
					array('name' => 'Tinglayan',),
				),
			),
			array(
				'name' => 'La Union',
				'areacode' => '72',
				'cities' => array(
					array('name' => 'San Fernando City',),
					array('name' => 'Agoo',),
					array('name' => 'Aringay',),
					array('name' => 'Bacnotan',),
					array('name' => 'Bagulin',),
					array('name' => 'Balaoan',),
					array('name' => 'Bangar',),
					array('name' => 'Bauang',),
					array('name' => 'Burgos',),
					array('name' => 'Caba',),
					array('name' => 'Luna',),
					array('name' => 'Naguilian',),
					array('name' => 'Pugo',),
					array('name' => 'Rosario',),
					array('name' => 'San Gabriel',),
					array('name' => 'San Juan',),
					array('name' => 'Santo Tomas',),
					array('name' => 'Santol',),
					array('name' => 'Sudipen',),
					array('name' => 'Tubao',),
				),
			),
			array(
				'name' => 'Laguna',
				'areacode' => '49',
				'cities' => array(
					array('name' => 'Calamba City',),
					array('name' => 'San Pablo City',),
					array('name' => 'Santa Rosa City',),
					array('name' => 'Alaminos',),
					array('name' => 'Bay',),
					array('name' => 'Biñan',),
					array('name' => 'Cabuyao',),
					array('name' => 'Calauan',),
					array('name' => 'Cavinti',),
					array('name' => 'Famy',),
					array('name' => 'Kalayaan',),
					array('name' => 'Liliw',),
					array('name' => 'Los Baños',),
					array('name' => 'Luisiana',),
					array('name' => 'Lumban',),
					array('name' => 'Mabitac',),
					array('name' => 'Magdalena',),
					array('name' => 'Majayjay',),
					array('name' => 'Nagcarlan',),
					array('name' => 'Paete',),
					array('name' => 'Pagsanjan',),
					array('name' => 'Pakil',),
					array('name' => 'Pangil',),
					array('name' => 'Pila',),
					array('name' => 'Rizal',),
					array('name' => 'San Pedro',),
					array('name' => 'Santa Cruz',),
					array('name' => 'Santa Maria',),
					array('name' => 'Siniloan',),
					array('name' => 'Victoria',),
				),
			),
			array(
				'name' => 'Lanao del Norte',
				'areacode' => '63',
				'cities' => array(
					array('name' => 'Iligan City',),
					array('name' => 'Bacolod',),
					array('name' => 'Baloi',),
					array('name' => 'Baroy',),
					array('name' => 'Kapatagan',),
					array('name' => 'Kauswagan',),
					array('name' => 'Kolambugan',),
					array('name' => 'Lala',),
					array('name' => 'Linamon',),
					array('name' => 'Magsaysay',),
					array('name' => 'Maigo',),
					array('name' => 'Matungao',),
					array('name' => 'Munai',),
					array('name' => 'Nunungan',),
					array('name' => 'Pantao Ragat',),
					array('name' => 'Pantar',),
					array('name' => 'Poona Piagapo',),
					array('name' => 'Salvador',),
					array('name' => 'Sapad',),
					array('name' => 'Sultan Naga Dimaporo',),
					array('name' => 'Tagoloan',),
					array('name' => 'Tangcal',),
					array('name' => 'Tubod',),
				),
			),
			array(
				'name' => 'Lanao del Sur',
				'areacode' => '63',
				'cities' => array(
					array('name' => 'Marawi City',),
					array('name' => 'Bacolod-Kalawi',),
					array('name' => 'Balabagan',),
					array('name' => 'Balindong',),
					array('name' => 'Bayang',),
					array('name' => 'Binidayan',),
					array('name' => 'Buadiposo-Buntong',),
					array('name' => 'Bubong',),
					array('name' => 'Bumbaran',),
					array('name' => 'Butig',),
					array('name' => 'Calanogas',),
					array('name' => 'Ditsaan-Ramain',),
					array('name' => 'Ganassi',),
					array('name' => 'Kapai',),
					array('name' => 'Kapatagan',),
					array('name' => 'Lumba-Bayabao',),
					array('name' => 'Lumbaca-Unayan',),
					array('name' => 'Lumbatan',),
					array('name' => 'Lumbayanague',),
					array('name' => 'Madalum',),
					array('name' => 'Madamba',),
					array('name' => 'Maguing',),
					array('name' => 'Malabang',),
					array('name' => 'Marantao',),
					array('name' => 'Marogong',),
					array('name' => 'Masiu',),
					array('name' => 'Mulondo',),
					array('name' => 'Pagayawan',),
					array('name' => 'Piagapo',),
					array('name' => 'Poona Bayabao',),
					array('name' => 'Pualas',),
					array('name' => 'Saguiaran',),
					array('name' => 'Sultan Dumalondong',),
					array('name' => 'Picong',),
					array('name' => 'Tagoloan II',),
					array('name' => 'Tamparan',),
					array('name' => 'Taraka',),
					array('name' => 'Tubaran',),
					array('name' => 'Tugaya',),
					array('name' => 'Wao',),
				),
			),
			array(
				'name' => 'Leyte',
				'areacode' => '53',
				'cities' => array(
					array('name' => 'Ormoc City',),
					array('name' => 'Tacloban City',),
					array('name' => 'Abuyog',),
					array('name' => 'Alangalang',),
					array('name' => 'Albuera',),
					array('name' => 'Babatngon',),
					array('name' => 'Barugo',),
					array('name' => 'Bato',),
					array('name' => 'Baybay',),
					array('name' => 'Burauen',),
					array('name' => 'Calubian',),
					array('name' => 'Capoocan',),
					array('name' => 'Carigara',),
					array('name' => 'Dagami',),
					array('name' => 'Dulag',),
					array('name' => 'Hilongos',),
					array('name' => 'Hindang',),
					array('name' => 'Inopacan',),
					array('name' => 'Isabel',),
					array('name' => 'Jaro',),
					array('name' => 'Javier',),
					array('name' => 'Julita',),
					array('name' => 'Kananga',),
					array('name' => 'La Paz',),
					array('name' => 'Leyte',),
					array('name' => 'Macarthur',),
					array('name' => 'Mahaplag',),
					array('name' => 'Matag-ob',),
					array('name' => 'Matalom',),
					array('name' => 'Mayorga',),
					array('name' => 'Merida',),
					array('name' => 'Palo',),
					array('name' => 'Palompon',),
					array('name' => 'Pastrana',),
					array('name' => 'San Isidro',),
					array('name' => 'San Miguel',),
					array('name' => 'Santa Fe',),
					array('name' => 'Tabango',),
					array('name' => 'Tabontabon',),
					array('name' => 'Tanauan',),
					array('name' => 'Tolosa',),
					array('name' => 'Tunga',),
					array('name' => 'Villaba',),
				),
			),
			array(
				'name' => 'Maguindanao',
				'areacode' => '64',
				'cities' => array(
					array('name' => 'Cotabato City',),
					array('name' => 'Ampatuan',),
					array('name' => 'Barira',),
					array('name' => 'Buldon',),
					array('name' => 'Buluan',),
					array('name' => 'Datu Abdullah Sangki',),
					array('name' => 'Datu Anggal Midtimbang',),
					array('name' => 'Datu Blah T. Sinsuat',),
					array('name' => 'Datu Hoffer Ampatuan',),
					array('name' => 'Datu Odin Sinsuat',),
					array('name' => 'Datu Paglas',),
					array('name' => 'Datu Piang',),
					array('name' => 'Datu Salibo',),
					array('name' => 'Datu Saudi-Ampatuan',),
					array('name' => 'Datu Unsay',),
					array('name' => 'Gen. S. K. Pendatun',),
					array('name' => 'Guindulungan',),
					array('name' => 'Kabuntalan',),
					array('name' => 'Mamasapano',),
					array('name' => 'Mangudadatu',),
					array('name' => 'Matanog',),
					array('name' => 'Northern Kabuntalan',),
					array('name' => 'Pagagawan',),
					array('name' => 'Pagalungan',),
					array('name' => 'Paglat',),
					array('name' => 'Pandag',),
					array('name' => 'Parang',),
					array('name' => 'Rajah Buayan',),
					array('name' => 'Shariff Aguak',),
					array('name' => 'Shariff Saydona Mustapha',),
					array('name' => 'South Upi',),
					array('name' => 'Sultan Kudarat',),
					array('name' => 'Sultan sa Barongis',),
					array('name' => 'Sultan Mastura',),
					array('name' => 'Talayan',),
					array('name' => 'Talitay',),
					array('name' => 'Upi',),
				),
			),
			array(
				'name' => 'Marinduque',
				'areacode' => '42',
				'cities' => array(
					array('name' => 'Boac',),
					array('name' => 'Buenavista',),
					array('name' => 'Gasan',),
					array('name' => 'Mogpog',),
					array('name' => 'Santa Cruz',),
					array('name' => 'Torrijos',),
				),
			),
			array(
				'name' => 'Masbate',
				'areacode' => '56',
				'cities' => array(
					array('name' => 'Masbate City',),
					array('name' => 'Aroroy',),
					array('name' => 'Baleno',),
					array('name' => 'Balud',),
					array('name' => 'Batuan',),
					array('name' => 'Cataingan',),
					array('name' => 'Cawayan',),
					array('name' => 'Claveria',),
					array('name' => 'Dimasalang',),
					array('name' => 'Esperanza',),
					array('name' => 'Mandaon',),
					array('name' => 'Milagros',),
					array('name' => 'Mobo',),
					array('name' => 'Monreal',),
					array('name' => 'Palanas',),
					array('name' => 'Pio V. Corpuz',),
					array('name' => 'Placer',),
					array('name' => 'San Fernando',),
					array('name' => 'San Jacinto',),
					array('name' => 'San Pascual',),
					array('name' => 'Uson',),
				),
			),
			array(
				'name' => 'Metro Manila',
				'areacode' => '2',
				'cities' => array(
					array('name' => 'Caloocan',),
					array('name' => 'Las Piñas',),
					array('name' => 'Makati',),
					array('name' => 'Malabon',),
					array('name' => 'Mandaluyong',),
					array('name' => 'Manila',),
					array('name' => 'Marikina',),
					array('name' => 'Muntinlupa',),
					array('name' => 'Navotas',),
					array('name' => 'Parañaque',),
					array('name' => 'Pasay',),
					array('name' => 'Pasig',),
					array('name' => 'Quezon City',),
					array('name' => 'San Juan',),
					array('name' => 'Taguig',),
					array('name' => 'Valenzuela',),
					array('name' => 'Pateros',),
				),
			),
			array(
				'name' => 'Misamis Occidental',
				'areacode' => '88',
				'cities' => array(
					array('name' => 'Oroquieta City',),
					array('name' => 'Ozamiz City',),
					array('name' => 'Tangub City',),
					array('name' => 'Aloran',),
					array('name' => 'Baliangao',),
					array('name' => 'Bonifacio',),
					array('name' => 'Calamba',),
					array('name' => 'Clarin',),
					array('name' => 'Concepcion',),
					array('name' => 'Don Victoriano Chiongbian',),
					array('name' => 'Jimenez',),
					array('name' => 'Lopez Jaena',),
					array('name' => 'Panaon',),
					array('name' => 'Plaridel',),
					array('name' => 'Sapang Dalaga',),
					array('name' => 'Sinacaban',),
					array('name' => 'Tudela',),
				),
			),
			array(
				'name' => 'Misamis Oriental',
				'areacode' => '88',
				'cities' => array(
					array('name' => 'Cagayan de Oro',),
					array('name' => 'Gingoog City',),
					array('name' => 'Alubijid',),
					array('name' => 'Balingasag',),
					array('name' => 'Balingoan',),
					array('name' => 'Binuangan',),
					array('name' => 'Claveria',),
					array('name' => 'El Salvador',),
					array('name' => 'Gitagum',),
					array('name' => 'Initao',),
					array('name' => 'Jasaan',),
					array('name' => 'Kinoguitan',),
					array('name' => 'Lagonglong',),
					array('name' => 'Laguindingan',),
					array('name' => 'Libertad',),
					array('name' => 'Lugait',),
					array('name' => 'Magsaysay',),
					array('name' => 'Manticao',),
					array('name' => 'Medina',),
					array('name' => 'Naawan',),
					array('name' => 'Opol',),
					array('name' => 'Salay',),
					array('name' => 'Sugbongcogon',),
					array('name' => 'Tagoloan',),
					array('name' => 'Talisayan',),
					array('name' => 'Villanueva',),
				),
			),
			array(
				'name' => 'Mountain Province',
				'areacode' => '74',
				'cities' => array(
					array('name' => 'Barlig',),
					array('name' => 'Bauko',),
					array('name' => 'Besao',),
					array('name' => 'Bontoc',),
					array('name' => 'Natonin',),
					array('name' => 'Paracelis',),
					array('name' => 'Sabangan',),
					array('name' => 'Sadanga',),
					array('name' => 'Sagada',),
					array('name' => 'Tadian',),
				),
			),
			array(
				'name' => 'Negros Occidental',
				'areacode' => '34',
				'cities' => array(
					array('name' => 'Bacolod City',),
					array('name' => 'Bago City',),
					array('name' => 'Cadiz City',),
					array('name' => 'Escalante City',),
					array('name' => 'Himamaylan City',),
					array('name' => 'Kabankalan City',),
					array('name' => 'La Carlota City',),
					array('name' => 'Sagay City',),
					array('name' => 'San Carlos City',),
					array('name' => 'Silay City',),
					array('name' => 'Sipalay City',),
					array('name' => 'Talisay City',),
					array('name' => 'Victorias City',),
					array('name' => 'Binalbagan',),
					array('name' => 'Calatrava',),
					array('name' => 'Candoni',),
					array('name' => 'Cauayan',),
					array('name' => 'Enrique B. Magalona',),
					array('name' => 'Hinigaran',),
					array('name' => 'Hinoba-an',),
					array('name' => 'Ilog',),
					array('name' => 'Isabela',),
					array('name' => 'La Castellana',),
					array('name' => 'Manapla',),
					array('name' => 'Moises Padilla',),
					array('name' => 'Murcia',),
					array('name' => 'Pontevedra',),
					array('name' => 'Pulupandan',),
					array('name' => 'Salvador Benedicto',),
					array('name' => 'San Enrique',),
					array('name' => 'Toboso',),
					array('name' => 'Valladolid',),
				),
			),
			array(
				'name' => 'Negros Oriental',
				'areacode' => '35',
				'cities' => array(
					array('name' => 'Bais',),
					array('name' => 'Bayawan',),
					array('name' => 'Canlaon',),
					array('name' => 'Dumaguete',),
					array('name' => 'Tanjay',),
					array('name' => 'Amlan',),
					array('name' => 'Ayungon',),
					array('name' => 'Bacong',),
					array('name' => 'Basay',),
					array('name' => 'Bindoy',),
					array('name' => 'Dauin',),
					array('name' => 'Guihulngan',),
					array('name' => 'Jimalalud',),
					array('name' => 'La Libertad',),
					array('name' => 'Mabinay',),
					array('name' => 'Manjuyod',),
					array('name' => 'Pamplona',),
					array('name' => 'San Jose',),
					array('name' => 'Santa Catalina',),
					array('name' => 'Siaton',),
					array('name' => 'Sibulan',),
					array('name' => 'Tayasan',),
					array('name' => 'Valencia',),
					array('name' => 'Vallehermoso',),
					array('name' => 'Zamboanguita',),
				),
			),
			array(
				'name' => 'Northern Samar',
				'areacode' => '55',
				'cities' => array(
					array('name' => 'Allen',),
					array('name' => 'Biri',),
					array('name' => 'Bobon',),
					array('name' => 'Capul',),
					array('name' => 'Catarman',),
					array('name' => 'Catubig',),
					array('name' => 'Gamay',),
					array('name' => 'Laoang',),
					array('name' => 'Lapinig',),
					array('name' => 'Las Navas',),
					array('name' => 'Lavezares',),
					array('name' => 'Lope de Vega',),
					array('name' => 'Mapanas',),
					array('name' => 'Mondragon',),
					array('name' => 'Palapag',),
					array('name' => 'Pambujan',),
					array('name' => 'Rosario',),
					array('name' => 'San Antonio',),
					array('name' => 'San Isidro',),
					array('name' => 'San Jose',),
					array('name' => 'San Roque',),
					array('name' => 'San Vicente',),
					array('name' => 'Silvino Lobos',),
					array('name' => 'Victoria',),
				),
			),
			array(
				'name' => 'Nueva Ecija',
				'areacode' => '44',
				'cities' => array(
					array('name' => 'Cabanatuan City',),
					array('name' => 'Gapan City',),
					array('name' => 'Science City of Muñoz',),
					array('name' => 'Palayan City',),
					array('name' => 'San Jose City',),
					array('name' => 'Aliaga',),
					array('name' => 'Bongabon',),
					array('name' => 'Cabiao',),
					array('name' => 'Carranglan',),
					array('name' => 'Cuyapo',),
					array('name' => 'Gabaldon',),
					array('name' => 'General Mamerto Natividad',),
					array('name' => 'General Tinio',),
					array('name' => 'Guimba',),
					array('name' => 'Jaen',),
					array('name' => 'Laur',),
					array('name' => 'Licab',),
					array('name' => 'Llanera',),
					array('name' => 'Lupao',),
					array('name' => 'Nampicuan',),
					array('name' => 'Pantabangan',),
					array('name' => 'Peñaranda',),
					array('name' => 'Quezon',),
					array('name' => 'Rizal',),
					array('name' => 'San Antonio',),
					array('name' => 'San Isidro',),
					array('name' => 'San Leonardo',),
					array('name' => 'Santa Rosa',),
					array('name' => 'Santo Domingo',),
					array('name' => 'Talavera',),
					array('name' => 'Talugtug',),
					array('name' => 'Zaragoza',),
				),
			),
			array(
				'name' => 'Nueva Vizcaya',
				'areacode' => '78',
				'cities' => array(
					array('name' => 'Alfonso Castaneda',),
					array('name' => 'Ambaguio',),
					array('name' => 'Aritao',),
					array('name' => 'Bagabag',),
					array('name' => 'Bambang',),
					array('name' => 'Bayombong',),
					array('name' => 'Diadi',),
					array('name' => 'Dupax del Norte',),
					array('name' => 'Dupax del Sur',),
					array('name' => 'Kasibu',),
					array('name' => 'Kayapa',),
					array('name' => 'Quezon',),
					array('name' => 'Santa Fe',),
					array('name' => 'Solano',),
					array('name' => 'Villaverde',),
				),
			),
			array(
				'name' => 'Occidental Mindoro',
				'areacode' => '43',
				'cities' => array(
					array('name' => 'Abra de Ilog',),
					array('name' => 'Calintaan',),
					array('name' => 'Looc',),
					array('name' => 'Lubang',),
					array('name' => 'Magsaysay',),
					array('name' => 'Mamburao',),
					array('name' => 'Paluan',),
					array('name' => 'Rizal',),
					array('name' => 'Sablayan',),
					array('name' => 'San Jose',),
					array('name' => 'Santa Cruz',),
				),
			),
			array(
				'name' => 'Oriental Mindoro',
				'areacode' => '43',
				'cities' => array(
					array('name' => 'Calapan City',),
					array('name' => 'Baco',),
					array('name' => 'Bansud',),
					array('name' => 'Bongabong',),
					array('name' => 'Bulalacao',),
					array('name' => 'Gloria',),
					array('name' => 'Mansalay',),
					array('name' => 'Naujan',),
					array('name' => 'Pinamalayan',),
					array('name' => 'Pola',),
					array('name' => 'Puerto Galera',),
					array('name' => 'Roxas',),
					array('name' => 'San Teodoro',),
					array('name' => 'Socorro',),
					array('name' => 'Victoria',),
				),
			),
			array(
				'name' => 'Palawan',
				'areacode' => '48',
				'cities' => array(
					array('name' => 'Puerto Princesa City',),
					array('name' => 'Aborlan',),
					array('name' => 'Agutaya',),
					array('name' => 'Araceli',),
					array('name' => 'Balabac',),
					array('name' => 'Bataraza',),
					array('name' => 'Brooke\'s Point',),
					array('name' => 'Busuanga',),
					array('name' => 'Cagayancillo',),
					array('name' => 'Coron',),
					array('name' => 'Culion',),
					array('name' => 'Cuyo',),
					array('name' => 'Dumaran',),
					array('name' => 'El Nido',),
					array('name' => 'Kalayaan',),
					array('name' => 'Linapacan',),
					array('name' => 'Magsaysay',),
					array('name' => 'Narra',),
					array('name' => 'Quezon',),
					array('name' => 'Rizal',),
					array('name' => 'Roxas',),
					array('name' => 'San Vicente',),
					array('name' => 'Sofronio Española',),
					array('name' => 'Taytay',),
				),
			),
			array(
				'name' => 'Pampanga',
				'areacode' => '45',
				'cities' => array(
					array('name' => 'Angeles City',),
					array('name' => 'City of San Fernando',),
					array('name' => 'Apalit',),
					array('name' => 'Arayat',),
					array('name' => 'Bacolor',),
					array('name' => 'Candaba',),
					array('name' => 'Floridablanca',),
					array('name' => 'Guagua',),
					array('name' => 'Lubao',),
					array('name' => 'Mabalacat',),
					array('name' => 'Macabebe',),
					array('name' => 'Magalang',),
					array('name' => 'Masantol',),
					array('name' => 'Mexico',),
					array('name' => 'Minalin',),
					array('name' => 'Porac',),
					array('name' => 'San Luis',),
					array('name' => 'San Simon',),
					array('name' => 'Santa Ana',),
					array('name' => 'Santa Rita',),
					array('name' => 'Santo Tomas',),
					array('name' => 'Sasmuan',),
				),
			),
			array(
				'name' => 'Pangasinan',
				'areacode' => '75',
				'cities' => array(
					array('name' => 'Alaminos City',),
					array('name' => 'Dagupan City',),
					array('name' => 'San Carlos City',),
					array('name' => 'Urdaneta City',),
					array('name' => 'Agno',),
					array('name' => 'Aguilar',),
					array('name' => 'Alcala',),
					array('name' => 'Anda',),
					array('name' => 'Asingan',),
					array('name' => 'Balungao',),
					array('name' => 'Bani',),
					array('name' => 'Basista',),
					array('name' => 'Bautista',),
					array('name' => 'Bayambang',),
					array('name' => 'Binalonan',),
					array('name' => 'Binmaley',),
					array('name' => 'Bolinao',),
					array('name' => 'Bugallon',),
					array('name' => 'Burgos',),
					array('name' => 'Calasiao',),
					array('name' => 'Dasol',),
					array('name' => 'Infanta',),
					array('name' => 'Labrador',),
					array('name' => 'Laoac',),
					array('name' => 'Lingayen',),
					array('name' => 'Mabini',),
					array('name' => 'Malasiqui',),
					array('name' => 'Manaoag',),
					array('name' => 'Mangaldan',),
					array('name' => 'Mangatarem',),
					array('name' => 'Mapandan',),
					array('name' => 'Natividad',),
					array('name' => 'Pozzorubio',),
					array('name' => 'Rosales',),
					array('name' => 'San Fabian',),
					array('name' => 'San Jacinto',),
					array('name' => 'San Manuel',),
					array('name' => 'San Nicolas',),
					array('name' => 'San Quintin',),
					array('name' => 'Santa Barbara',),
					array('name' => 'Santa Maria',),
					array('name' => 'Santo Tomas',),
					array('name' => 'Sison',),
					array('name' => 'Sual',),
					array('name' => 'Tayug',),
					array('name' => 'Umingan',),
					array('name' => 'Urbiztondo',),
					array('name' => 'Villasis',),
				),
			),
			array(
				'name' => 'Quezon',
				'areacode' => '42',
				'cities' => array(
					array('name' => 'Lucena City',),
					array('name' => 'Agdangan',),
					array('name' => 'Alabat',),
					array('name' => 'Atimonan',),
					array('name' => 'Buenavista',),
					array('name' => 'Burdeos',),
					array('name' => 'Calauag',),
					array('name' => 'Candelaria',),
					array('name' => 'Catanauan',),
					array('name' => 'Dolores',),
					array('name' => 'General Luna',),
					array('name' => 'General Nakar',),
					array('name' => 'Guinayangan',),
					array('name' => 'Gumaca',),
					array('name' => 'Infanta',),
					array('name' => 'Jomalig',),
					array('name' => 'Lopez',),
					array('name' => 'Lucban',),
					array('name' => 'Macalelon',),
					array('name' => 'Mauban',),
					array('name' => 'Mulanay',),
					array('name' => 'Padre Burgos',),
					array('name' => 'Pagbilao',),
					array('name' => 'Panukulan',),
					array('name' => 'Patnanungan',),
					array('name' => 'Perez',),
					array('name' => 'Pitogo',),
					array('name' => 'Plaridel',),
					array('name' => 'Polillo',),
					array('name' => 'Quezon',),
					array('name' => 'Real',),
					array('name' => 'Sampaloc',),
					array('name' => 'San Andres',),
					array('name' => 'San Antonio',),
					array('name' => 'San Francisco',),
					array('name' => 'San Narciso',),
					array('name' => 'Sariaya',),
					array('name' => 'Tagkawayan',),
					array('name' => 'Tayabas',),
					array('name' => 'Tiaong',),
					array('name' => 'Unisan',),
				),
			),
			array(
				'name' => 'Quirino',
				'areacode' => '78',
				'cities' => array(
					array('name' => 'Aglipay',),
					array('name' => 'Cabarroguis',),
					array('name' => 'Diffun',),
					array('name' => 'Maddela',),
					array('name' => 'Nagtipunan',),
					array('name' => 'Saguday',),
				),
			),
			array(
				'name' => 'Rizal',
				'areacode' => '2',
				'cities' => array(
					array('name' => 'Antipolo City',),
					array('name' => 'Angono',),
					array('name' => 'Baras',),
					array('name' => 'Binangonan',),
					array('name' => 'Cainta',),
					array('name' => 'Cardona',),
					array('name' => 'Jalajala',),
					array('name' => 'Morong',),
					array('name' => 'Pililla',),
					array('name' => 'Rodriguez',),
					array('name' => 'San Mateo',),
					array('name' => 'Tanay',),
					array('name' => 'Taytay',),
					array('name' => 'Teresa',),
				),
			),
			array(
				'name' => 'Romblon',
				'areacode' => '42',
				'cities' => array(
					array('name' => 'Alcantara',),
					array('name' => 'Banton',),
					array('name' => 'Cajidiocan',),
					array('name' => 'Calatrava',),
					array('name' => 'Concepcion',),
					array('name' => 'Corcuera',),
					array('name' => 'Ferrol',),
					array('name' => 'Looc',),
					array('name' => 'Magdiwang',),
					array('name' => 'Odiongan',),
					array('name' => 'Romblon',),
					array('name' => 'San Agustin',),
					array('name' => 'San Andres',),
					array('name' => 'San Fernando',),
					array('name' => 'San Jose',),
					array('name' => 'Santa Fe',),
					array('name' => 'Santa Maria',),
				),
			),
			array(
				'name' => 'Samar',
				'areacode' => '55',
				'cities' => array(
					array('name' => 'Calbayog City',),
					array('name' => 'Almagro',),
					array('name' => 'Basey',),
					array('name' => 'Calbiga',),
					array('name' => 'Catbalogan',),
					array('name' => 'Daram',),
					array('name' => 'Gandara',),
					array('name' => 'Hinabangan',),
					array('name' => 'Jiabong',),
					array('name' => 'Marabut',),
					array('name' => 'Matuguinao',),
					array('name' => 'Motiong',),
					array('name' => 'Pagsanghan',),
					array('name' => 'Paranas',),
					array('name' => 'Pinabacdao',),
					array('name' => 'San Jorge',),
					array('name' => 'San Jose De Buan',),
					array('name' => 'San Sebastian',),
					array('name' => 'Santa Margarita',),
					array('name' => 'Santa Rita',),
					array('name' => 'Santo Niño',),
					array('name' => 'Tagapul-an',),
					array('name' => 'Talalora',),
					array('name' => 'Tarangnan',),
					array('name' => 'Villareal',),
					array('name' => 'Zumarraga',),
				),
			),
			array(
				'name' => 'Sarangani',
				'areacode' => '83',
				'cities' => array(
					array('name' => 'Alabel',),
					array('name' => 'Glan',),
					array('name' => 'Kiamba',),
					array('name' => 'Maasim',),
					array('name' => 'Maitum',),
					array('name' => 'Malapatan',),
					array('name' => 'Malungon',),
				),
			),
			array(
				'name' => 'Siquijor',
				'areacode' => '35',
				'cities' => array(
					array('name' => 'Enrique Villanueva',),
					array('name' => 'Larena',),
					array('name' => 'Lazi',),
					array('name' => 'Maria',),
					array('name' => 'San Juan',),
					array('name' => 'Siquijor',),
				),
			),
			array(
				'name' => 'Sorsogon',
				'areacode' => '56',
				'cities' => array(
					array('name' => 'Sorsogon City',),
					array('name' => 'Barcelona',),
					array('name' => 'Bulan',),
					array('name' => 'Bulusan',),
					array('name' => 'Casiguran',),
					array('name' => 'Castilla',),
					array('name' => 'Donsol',),
					array('name' => 'Gubat',),
					array('name' => 'Irosin',),
					array('name' => 'Juban',),
					array('name' => 'Magallanes',),
					array('name' => 'Matnog',),
					array('name' => 'Pilar',),
					array('name' => 'Prieto Diaz',),
					array('name' => 'Santa Magdalena',),
				),
			),
			array(
				'name' => 'South Cotabato',
				'areacode' => '83',
				'cities' => array(
					array('name' => 'General Santos City',),
					array('name' => 'Koronadal City',),
					array('name' => 'Banga',),
					array('name' => 'Lake Sebu',),
					array('name' => 'Norala',),
					array('name' => 'Polomolok',),
					array('name' => 'Santo Niño',),
					array('name' => 'Surallah',),
					array('name' => 'T\'Boli',),
					array('name' => 'Tampakan',),
					array('name' => 'Tantangan',),
					array('name' => 'Tupi',),
				),
			),
			array(
				'name' => 'Southern Leyte',
				'areacode' => '53',
				'cities' => array(
					array('name' => 'Maasin City',),
					array('name' => 'Anahawan',),
					array('name' => 'Bontoc',),
					array('name' => 'Hinunangan',),
					array('name' => 'Hinundayan',),
					array('name' => 'Libagon',),
					array('name' => 'Liloan',),
					array('name' => 'Limasawa',),
					array('name' => 'Macrohon',),
					array('name' => 'Malitbog',),
					array('name' => 'Padre Burgos',),
					array('name' => 'Pintuyan',),
					array('name' => 'Saint Bernard',),
					array('name' => 'San Francisco',),
					array('name' => 'San Juan',),
					array('name' => 'San Ricardo',),
					array('name' => 'Silago',),
					array('name' => 'Sogod',),
					array('name' => 'Tomas Oppus',),
				),
			),
			array(
				'name' => 'Sultan Kudarat',
				'areacode' => '64',
				'cities' => array(
					array('name' => 'Tacurong City',),
					array('name' => 'Bagumbayan',),
					array('name' => 'Columbio',),
					array('name' => 'Esperanza',),
					array('name' => 'Isulan',),
					array('name' => 'Kalamansig',),
					array('name' => 'Lambayong',),
					array('name' => 'Lebak',),
					array('name' => 'Lutayan',),
					array('name' => 'Palimbang',),
					array('name' => 'President Quirino',),
					array('name' => 'Sen. Ninoy Aquino',),
				),
			),
			array(
				'name' => 'Sulu',
				'areacode' => '68',
				'cities' => array(
					array('name' => 'Banguingui',),
					array('name' => 'Hadji Panglima Tahil',),
					array('name' => 'Indanan',),
					array('name' => 'Jolo',),
					array('name' => 'Kalingalan Caluang',),
					array('name' => 'Lugus',),
					array('name' => 'Luuk',),
					array('name' => 'Maimbung',),
					array('name' => 'Old Panamao',),
					array('name' => 'Omar',),
					array('name' => 'Pandami',),
					array('name' => 'Panglima Estino',),
					array('name' => 'Pangutaran',),
					array('name' => 'Parang',),
					array('name' => 'Pata',),
					array('name' => 'Patikul',),
					array('name' => 'Siasi',),
					array('name' => 'Talipao',),
					array('name' => 'Tapul',),
				),
			),
			array(
				'name' => 'Surigao del Norte',
				'areacode' => '86',
				'cities' => array(
					array('name' => 'Surigao City',),
					array('name' => 'Alegria',),
					array('name' => 'Bacuag',),
					array('name' => 'Burgos',),
					array('name' => 'Claver',),
					array('name' => 'Dapa',),
					array('name' => 'Del Carmen',),
					array('name' => 'General Luna',),
					array('name' => 'Gigaquit',),
					array('name' => 'Mainit',),
					array('name' => 'Malimono',),
					array('name' => 'Pilar',),
					array('name' => 'Placer',),
					array('name' => 'San Benito',),
					array('name' => 'San Francisco',),
					array('name' => 'San Isidro',),
					array('name' => 'Santa Monica',),
					array('name' => 'Sison',),
					array('name' => 'Socorro',),
					array('name' => 'Tagana-an',),
					array('name' => 'Tubod',),
				),
			),
			array(
				'name' => 'Surigao del Sur',
				'areacode' => '86',
				'cities' => array(
					array('name' => 'Bislig City',),
					array('name' => 'Barobo',),
					array('name' => 'Bayabas',),
					array('name' => 'Cagwait',),
					array('name' => 'Cantilan',),
					array('name' => 'Carmen',),
					array('name' => 'Carrascal',),
					array('name' => 'Cortes',),
					array('name' => 'Hinatuan',),
					array('name' => 'Lanuza',),
					array('name' => 'Lianga',),
					array('name' => 'Lingig',),
					array('name' => 'Madrid',),
					array('name' => 'Marihatag',),
					array('name' => 'San Agustin',),
					array('name' => 'San Miguel',),
					array('name' => 'Tagbina',),
					array('name' => 'Tago',),
					array('name' => 'Tandag',),
				),
			),
			array(
				'name' => 'Tarlac',
				'areacode' => '45',
				'cities' => array(
					array('name' => 'Tarlac City',),
					array('name' => 'Anao',),
					array('name' => 'Bamban',),
					array('name' => 'Camiling',),
					array('name' => 'Capas',),
					array('name' => 'Concepcion',),
					array('name' => 'Gerona',),
					array('name' => 'La Paz',),
					array('name' => 'Mayantoc',),
					array('name' => 'Moncada',),
					array('name' => 'Paniqui',),
					array('name' => 'Pura',),
					array('name' => 'Ramos',),
					array('name' => 'San Clemente',),
					array('name' => 'San Jose',),
					array('name' => 'San Manuel',),
					array('name' => 'Santa Ignacia',),
					array('name' => 'Victoria',),
				),
			),
			array(
				'name' => 'Tawi-Tawi',
				'areacode' => '68',
				'cities' => array(
					array('name' => 'Bongao',),
					array('name' => 'Languyan',),
					array('name' => 'Mapun',),
					array('name' => 'Panglima Sugala',),
					array('name' => 'Sapa-Sapa',),
					array('name' => 'Sibutu',),
					array('name' => 'Simunul',),
					array('name' => 'Sitangkai',),
					array('name' => 'South Ubian',),
					array('name' => 'Tandubas',),
					array('name' => 'Turtle Islands',),
				),
			),
			array(
				'name' => 'Zambales',
				'areacode' => '47',
				'cities' => array(
					array('name' => 'Olongapo City',),
					array('name' => 'Botolan',),
					array('name' => 'Cabangan',),
					array('name' => 'Candelaria',),
					array('name' => 'Castillejos',),
					array('name' => 'Iba',),
					array('name' => 'Masinloc',),
					array('name' => 'Palauig',),
					array('name' => 'San Antonio',),
					array('name' => 'San Felipe',),
					array('name' => 'San Marcelino',),
					array('name' => 'San Narciso',),
					array('name' => 'Santa Cruz',),
					array('name' => 'Subic',),
				),
			),
			array(
				'name' => 'Zamboanga del Norte',
				'areacode' => '65',
				'cities' => array(
					array('name' => 'Dapitan City',),
					array('name' => 'Dipolog City',),
					array('name' => 'Bacungan',),
					array('name' => 'Baliguian',),
					array('name' => 'Godod',),
					array('name' => 'Gutalac',),
					array('name' => 'Jose Dalman',),
					array('name' => 'Kalawit',),
					array('name' => 'Katipunan',),
					array('name' => 'La Libertad',),
					array('name' => 'Labason',),
					array('name' => 'Liloy',),
					array('name' => 'Manukan',),
					array('name' => 'Mutia',),
					array('name' => 'Piñan',),
					array('name' => 'Polanco',),
					array('name' => 'Pres. Manuel A. Roxas',),
					array('name' => 'Rizal',),
					array('name' => 'Salug',),
					array('name' => 'Sergio Osmeña Sr.',),
					array('name' => 'Siayan',),
					array('name' => 'Sibuco',),
					array('name' => 'Sibutad',),
					array('name' => 'Sindangan',),
					array('name' => 'Siocon',),
					array('name' => 'Sirawai',),
					array('name' => 'Tampilisan',),
				),
			),
			array(
				'name' => 'Zamboanga del Sur',
				'areacode' => '62',
				'cities' => array(
					array('name' => 'Pagadian City',),
					array('name' => 'Zamboanga City',),
					array('name' => 'Aurora',),
					array('name' => 'Bayog',),
					array('name' => 'Dimataling',),
					array('name' => 'Dinas',),
					array('name' => 'Dumalinao',),
					array('name' => 'Dumingag',),
					array('name' => 'Guipos',),
					array('name' => 'Josefina',),
					array('name' => 'Kumalarang',),
					array('name' => 'Labangan',),
					array('name' => 'Lakewood',),
					array('name' => 'Lapuyan',),
					array('name' => 'Mahayag',),
					array('name' => 'Margosatubig',),
					array('name' => 'Midsalip',),
					array('name' => 'Molave',),
					array('name' => 'Pitogo',),
					array('name' => 'Ramon Magsaysay',),
					array('name' => 'San Miguel',),
					array('name' => 'San Pablo',),
					array('name' => 'Sominot',),
					array('name' => 'Tabina',),
					array('name' => 'Tambulig',),
					array('name' => 'Tigbao',),
					array('name' => 'Tukuran',),
					array('name' => 'Vincenzo A. Sagun',),
				),
			),
			array(
				'name' => 'Zamboanga Sibugay',
				'areacode' => '62',
				'cities' => array(
					array('name' => 'Alicia',),
					array('name' => 'Buug',),
					array('name' => 'Diplahan',),
					array('name' => 'Imelda',),
					array('name' => 'Ipil',),
					array('name' => 'Kabasalan',),
					array('name' => 'Mabuhay',),
					array('name' => 'Malangas',),
					array('name' => 'Naga',),
					array('name' => 'Olutanga',),
					array('name' => 'Payao',),
					array('name' => 'Roseller Lim',),
					array('name' => 'Siay',),
					array('name' => 'Talusan',),
					array('name' => 'Titay',),
					array('name' => 'Tungawan',),
				),
			),
		),
	),
);

?>